---
- hosts: "leaders, !leaders[0]" # all hosts in leaders except the first one
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
    - name: Copy join command to leaders nodes.
      become: yes
      become_method: sudo
      become_user: root
      copy:
        src: /tmp/kubernetes_join_leaders_command
        dest: /tmp/kubernetes_join_leaders_command
        mode: 0777

    - name: Join the Leaders nodes with leader.
      become: yes
      become_method: sudo
      become_user: root
      command: sh /tmp/kubernetes_join_leaders_command
      register: joined_or_not

    - debug:
        msg: "{{ joined_or_not.stdout }}"

- hosts: leaders
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
    - name: Configure kubectl command auto completion.
      lineinfile:
        dest: /home/{{ ansible_user }}/.bashrc
        line: "source <(kubectl completion bash)"
        insertafter: EOF
