---
- hosts: "leaders, workers"
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
    - name: Join the Worker nodes with leader.
      become: yes
      become_method: sudo
      become_user: root
      command: kubeadm reset -f
      ignore_errors: True
